In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

In [19]:
# Load vnl dataset
file_path = "../../data/input/1VNL_data.xlsx"
df_vnl = pd.read_excel(file_path, sheet_name="1VNL (LVT, LVP, VCT)", engine="openpyxl")

# Load dana1 dataset
file_path = "../../data/input/AF Commercial Data_100324.xlsx"
df_af = pd.read_excel(file_path, sheet_name="Item", engine="openpyxl")

# Load dana2 dataset
file_path = "../../data/input/AHF Contract Data_100424.xlsx"
df_ahf = pd.read_excel(file_path, sheet_name="Item", engine="openpyxl")

# Load dana3 dataset LVT Collections
file_path = "../../data/input/Mannington LVT Master List_Latest Version.xlsx"
df_man = pd.read_excel(file_path, sheet_name="LVT Collections", engine="openpyxl")

In [20]:
df_vnl.head(2)

,Range[site],Range[site_description],Range[supplier_no],Range[supplier_name],Range[invoice_id],Range[invoice_no],Range[date_posted],Range[project_id],Range[project_name],Range[account],...,Range[multiple_commodities],Range[priority_multiple_commodities],Range[all_invoice_priority_products_2008],Range[any_invoice_priority_products_2008],Range[freight_per_invoice],Range[priority_product_total],Range[non_priority_product_total],Range[percentage_priority],Range[percentage_non_priority],Range[pct_priority_greater_than_70]
0,SPCP,Spectra Coppell,108164,"Mannington Mills, Inc.",708328,98754742,2024-06-18,2405155306,"Shenandoah, TX - LVT & CPT Material",2008,...,False,False,True,True,468.88,11841.30,0.0,100.0,0.0,True
1,SPCP,Spectra Coppell,102775,"Interface Americas, Inc.",690888,2521874,2024-06-18,SPCP105923,RISD JJ Pearce - Phase 2,2008,...,False,False,True,True,148.16,920.32,0.0,100.0,0.0,True

In [21]:
#emove the range and bracket from the column names
df_vnl.columns = df_vnl.columns.str.replace(r"Range\[|\]", "", regex=True)
df_vnl.head(2)

,site,site_description,supplier_no,supplier_name,invoice_id,invoice_no,date_posted,project_id,project_name,account,...,multiple_commodities,priority_multiple_commodities,all_invoice_priority_products_2008,any_invoice_priority_products_2008,freight_per_invoice,priority_product_total,non_priority_product_total,percentage_priority,percentage_non_priority,pct_priority_greater_than_70
0,SPCP,Spectra Coppell,108164,"Mannington Mills, Inc.",708328,98754742,2024-06-18,2405155306,"Shenandoah, TX - LVT & CPT Material",2008,...,False,False,True,True,468.88,11841.30,0.0,100.0,0.0,True
1,SPCP,Spectra Coppell,102775,"Interface Americas, Inc.",690888,2521874,2024-06-18,SPCP105923,RISD JJ Pearce - Phase 2,2008,...,False,False,True,True,148.16,920.32,0.0,100.0,0.0,True

In [22]:
df_af.head(2)

,ItemNumber,ItemName_en,collectionType_en,DesignName_en,ItemDescription_en,categoryType_en,ItemBrand,usage_en,Color_en,ItemPrimarySalesChannel,...,Species_en,ItemPerformanceClass,FinishSystem_en,Gloss_en,Look_en,ItemCommercialColorCategoryVinyl,ItemUPC,cartonsPerPallet,ItemUnitCode,Concat Size
0,ST131641,Biome Tellus Solstice,Biome,Tellus,Biome Tellus Solstice,Dry Back LVT,Armstrong Flooring,Commercial,Solstice,Commercial,...,NaN,Premium,Diamond 10Â® Technology,Low Gloss,Traditional Wood,NaN,4.236999e+10,54.0,CTN,"6""x48"""
1,ST132641,Biome Tellus Midsummer,Biome,Tellus,Biome Tellus Midsummer,Dry Back LVT,Armstrong Flooring,Commercial,Midsummer,Commercial,...,NaN,Premium,Diamond 10Â® Technology,Low Gloss,Traditional Wood,NaN,4.236999e+10,54.0,CTN,"6""x48"""

In [23]:
# Count the number of instances where part_no from df_vnl exists in df_af['ItemNumber']
matching_count = df_vnl['part_no'].isin(df_af['ItemNumber']).sum()
print(f"Number of matching part numbers: {matching_count}")

Number of matching part numbers: 0

In [25]:
matching_count_ahf = df_vnl['part_no'].isin(df_ahf['ItemNumber']).sum()
print(f"Number of matching part numbers in df_ahf: {matching_count_ahf}")

Number of matching part numbers in df_ahf: 0

In [26]:
# Find part numbers in df_vnl where part_description contains ItemName_en from df_ahf
matching_parts = df_vnl[df_vnl['part_description'].str.contains('|'.join(df_ahf['ItemName_en']), case=False, na=False)]

# Display the matching part numbers
print(matching_parts[['part_no', 'part_description']])

Empty DataFrame
Columns: [part_no, part_description]
Index: []

In [27]:
# Find part numbers in df_vnl where part_description contains ItemName_en from df_af
matching_parts_af = df_vnl[df_vnl['part_description'].str.contains('|'.join(df_af['ItemName_en']), case=False, na=False)]

# Display the matching part numbers
print(matching_parts_af[['part_no', 'part_description']])

Empty DataFrame
Columns: [part_no, part_description]
Index: []